sigma('DT','NN',13635).
sigma('IN','DT',11534).
sigma('PRP','VBD',9573).
sigma('NN','IN',8798).
sigma('JJ','NN',7114).
sigma('NN','.',6527).
sigma('DT','JJ',6311).
sigma('.','PRP',6083).
sigma('IN','PRP',4482).
sigma('TO','VB',4457).
sigma('VBD','RB',3785).
sigma('NN','VBD',3439).
sigma('IN','NN',3415).
sigma('PRP','VBP',3323).
sigma('VBD','DT',3151).
sigma('VBD','IN',2960).
sigma('.','DT',2959).
sigma('NN','NN',2829).
sigma('NN','CC',2671).
sigma('RB','IN',2644).
sigma('PRP$','NN',2570).
sigma('NNS','IN',2455).
sigma('RB','.',2277).
sigma('RB','JJ',2273).
sigma('NNP','VBD',2240).
sigma('RB','RB',2236).
sigma('VBD','NNP',2172).
sigma('JJ','NNS',2167).
sigma('.','NNP',2102).
sigma('PRP','MD',2015).
sigma('IN','PRP$',1931).
sigma('PRP','.',1927).
sigma('MD','VB',1883).
sigma('VBD','VBN',1861).
sigma('NNP','.',1850).
sigma('RB','VB',1844).
sigma('VB','PRP',1842).
sigma('VBD','PRP',1798).
sigma('NNP','NNP',1785).
sigma('VBN','IN',1744).
sigma('NN','PRP',1726).
sigma('DT','NNS',1686).
sigma('NN','RB',1647).
sigma('VB','DT',1618).
sigma('CC','VBD',1587).
sigma('JJ','JJ',1541).
sigma('VB','IN',1529).
sigma('IN','JJ',1505).
sigma('RB','VBD',1426).
sigma('.','RB',1411).
sigma('PRP','RB',1409).
sigma('NNS','.',1383).
sigma('DT','NNP',1369).
sigma('JJ','IN',1335).
sigma('VBD','TO',1264).
sigma('RB','VBN',1222).
sigma('.','IN',1219).
sigma('VBG','IN',1218).
sigma('JJ','.',1218).
sigma('IN','NNP',1214).
sigma('VBD','VBG',1208).
sigma('IN','IN',1196).
sigma('CC','RB',1189).
sigma('VBD','.',1134).
sigma('PRP','IN',1125).
sigma('PRP','VBZ',1109).
sigma('RB','PRP',1093).
sigma('RB','DT',1079).
sigma('JJ','CC',998).
sigma('NNS','VBD',996).
sigma('VBP','RB',995).
sigma('VBP','PRP',969).
sigma('CC','DT',938).
sigma('CC','PRP',933).
sigma('NN','WDT',915).
sigma('MD','RB',908).
sigma('NN','DT',900).
sigma('NN','NNS',898).
sigma('NN','TO',889).
sigma('IN','NNS',889).
sigma('PRP$','NNS',888).
sigma('NN','VBZ',888).
sigma('NNS','CC',854).
sigma('TO','DT',853).
sigma('VBZ','RB',832).
sigma('VBD','JJ',804).
sigma('VBD','RP',770).
sigma('VB','.',752).
sigma('WDT','VBD',750).
sigma('NNP','IN',750).
sigma('.','UH',749).
sigma('.','VBD',735).
sigma('IN','VBG',734).
sigma('.','VB',732).
sigma('PRP$','JJ',731).
sigma('RB','CC',726).
sigma('IN','RB',725).
sigma('.','CC',724).
sigma('DT','RB',714).
sigma('RB','VBG',713).
sigma('PRP','VB',706).
sigma('VB','RB',698).
sigma('VBZ','DT',676).
sigma('.','NN',675).
sigma('VBG','DT',663).
sigma('CC','JJ',659).
sigma('RP','IN',651).
sigma('VBD','PRP$',649).
sigma('VBG','TO',647).
sigma('VBG','RB',636).
sigma('NN','VBG',610).
sigma('CC','NN',608).
sigma('VB','VBN',606).
sigma('VBG','NN',592).
sigma('VB','TO',588).
sigma('DT','VBD',586).
sigma('VBN','TO',584).
sigma('CD','NNS',582).
sigma('CC','IN',579).
sigma('WRB','PRP',565).
sigma('NNP','RB',551).
sigma('RB','TO',532).
sigma('NNP','CC',530).
sigma('NNP','VBZ',525).
sigma('VBD','CC',522).
sigma('NNS','RB',515).
sigma('JJ','TO',514).
sigma('IN','.',511).
sigma('.','JJ',509).
sigma('NN','JJ',505).
sigma('VBD','NN',502).
sigma('VBN','DT',487).
sigma('DT','VBZ',484).
sigma('VBN','.',482).
sigma('VBZ','NN',467).
sigma('PRP','DT',466).
sigma('NNP','NN',458).
sigma('DT','IN',456).
sigma('TO','PRP',452).
sigma('WP','PRP',445).
sigma('CC','VB',445).
sigma('PRP','CC',444).
sigma('VBN','RB',442).
sigma('DT','.',440).
sigma('WP','VBD',437).
sigma('VBP','DT',437).
sigma('VBZ','IN',433).
sigma('VBP','IN',433).
sigma('JJ','PRP',432).
sigma('VBP','VBN',431).
sigma('IN','CD',426).
sigma('NNP','PRP',425).
sigma('VB','RP',402).
sigma('VB','NN',398).
sigma('NNS','PRP',398).
sigma('EX','VBD',398).
sigma('VBG','PRP',389).
sigma('VB','JJ',376).
sigma('.','WP',370).
sigma('VB','PRP$',366).
sigma('CD','IN',366).
sigma('VBZ','JJ',363).
sigma('.','WRB',358).
sigma('NNS','VBP',348).
sigma('VBN','PRP',340).
sigma('VBN','NN',337).
sigma('DT','VBG',330).
sigma('JJ','RB',328).
sigma('PDT','DT',327).
sigma('RP','DT',322).
sigma('IN','TO',319).
sigma('NN','VBN',312).
sigma('NN','MD',311).
sigma('PRP','TO',308).
sigma('VBG','.',307).
sigma('CC','VBG',303).
sigma('RB','NN',300).
sigma('NN','NNP',299).
sigma('CC','NNP',297).
sigma('VBG','NNS',294).
sigma('.','EX',294).
sigma('VBP','.',293).
sigma('VBZ','PRP',289).
sigma('VB','CC',289).
sigma('DT','CD',285).
sigma('JJ','NNP',282).
sigma('IN','WDT',282).
sigma('NNS','WDT',280).
sigma('RP','.',277).
sigma('.','PRP$',277).
sigma('VBN','VBN',273).
sigma('PRP','PRP',267).
sigma('RB','VBP',264).
sigma('VBP','TO',258).
sigma('CD','NN',257).
sigma('VBP','VBG',253).
sigma('JJ','VBG',252).
sigma('NNP','DT',251).
sigma('VBN','CC',248).
sigma('TO','PRP$',248).
sigma('NNS','VBG',245).
sigma('VBN','RP',243).
sigma('NNP','VBG',242).
sigma('VBG','JJ',240).
sigma('WP','VBZ',238).
sigma('UH','.',238).
sigma('CC','NNS',238).
sigma('PRP','RP',237).
sigma('RB','VBZ',234).
sigma('NNS','DT',234).
sigma('WDT','VBZ',233).
sigma('TO','NN',232).
sigma('CC','VBN',232).
sigma('IN','CC',223).
sigma('VBG','RP',222).
sigma('NNP','NNS',220).
sigma('JJ','VBD',220).
sigma('WDT','PRP',218).
sigma('VB','VBG',218).
sigma('NNS','NN',217).
sigma('PRP','VBG',216).
sigma('VBZ','VBN',212).
sigma('VBP','JJ',212).
sigma('VBG','PRP$',212).
sigma('MD','PRP',208).
sigma('.','WDT',207).
sigma('CD','CD',207).
sigma('WP','VBP',201).
sigma('NN','WP',198).
sigma('VBN','VBG',194).
sigma('DT','VBN',192).
sigma('VBZ','NNP',191).
sigma('VBN','NNP',190).
sigma('VB','WP',189).
sigma('UH','PRP',187).
sigma('WRB','DT',186).
sigma('DT','PRP',184).
sigma('TO','NNP',181).
sigma('VB','VBD',180).
sigma('NNS','TO',179).
sigma('NN','WRB',178).
sigma('DT','JJS',178).
sigma('RP','RB',173).
sigma('NNP','TO',173).
sigma('NN','VBP',170).
sigma('JJ','CD',169).
sigma('NN','VB',163).
sigma('.','CD',163).
sigma('VBN','JJ',161).
sigma('IN','WP',157).
sigma('VBZ','VBG',155).
sigma('NNS','VBN',154).
sigma('.','NNS',154).
sigma('JJ','DT',153).
sigma('CD','JJ',153).
sigma('VBD','NNS',151).
sigma('PRP','JJ',147).
sigma('EX','VBZ',146).
sigma('VBP','NN',144).
sigma('WP','DT',142).
sigma('VBG','CC',142).
sigma('NNS','JJ',138).
sigma('JJ','VBN',137).
sigma('WDT','.',136).
sigma('IN','JJS',136).
sigma('CD','.',133).
sigma('VBG','VBN',131).
sigma('NNP','MD',131).
sigma('VBD','CD',130).
sigma('RB','CD',130).
sigma('NN','CD',129).
sigma('VB','NNS',128).
sigma('VBZ','TO',127).
sigma('.','VBG',126).
sigma('CC','PRP$',126).
sigma('CC','CD',126).
sigma('VBZ','.',124).
sigma('IN','EX',124).
sigma('WRB','VBP',123).
sigma('RP','TO',123).
sigma('RB','WP',122).
sigma('CC','WRB',122).
sigma('VB','WRB',121).
sigma('PRP','NN',121).
sigma('WDT','RB',120).
sigma('NNS','NNS',120).
sigma('IN','PDT',119).
sigma('RBS','JJ',118).
sigma('NN','PRP$',118).
sigma('JJR','IN',118).
sigma('WDT','MD',116).
sigma('DT','JJR',115).
sigma('VBN','PRP$',114).
sigma('JJS','NN',113).
sigma('CD','CC',113).
sigma('NNS','MD',112).
sigma('IN','VBN',112).
sigma('.','VBZ',110).
sigma('UH','VBD',110).
sigma('VBN','NNS',109).
sigma('VBD','VBD',108).
sigma('RB','WRB',108).
sigma('RBR','JJ',107).
sigma('.','MD',107).
sigma('VBD','WP',106).
sigma('DT','DT',105).
sigma('IN','WRB',104).
sigma('WDT','NN',103).
sigma('RP','CC',103).
sigma('CC','WP',103).
sigma('WDT','DT',102).
sigma('VBP','VBD',102).
sigma('NNP','WP',102).
sigma('RP','PRP$',101).
sigma('WRB','JJ',100).
sigma('UH','RB',100).
sigma('RB','NNP',98).
sigma('IN','VBD',98).
sigma('VB','NNP',96).
sigma('VBD','WRB',96).
sigma('WDT','NNP',91).
sigma('JJS','IN',90).
sigma('RB','PRP$',89).
sigma('DT','RBS',89).
sigma('JJR','NN',88).
sigma('NNS','WP',87).
sigma('.','VBP',86).
sigma('.','VBN',86).
sigma('DT','VBP',86).
sigma('PRP','VBN',83).
sigma('CC','VBP',83).
sigma('NNP','VB',81).
sigma('RB','RBR',80).
sigma('MD','VBD',80).
sigma('RB','MD',75).
sigma('PRP','WP',75).
sigma('VBZ','WP',74).
sigma('VBG','VBD',74).
sigma('DT','NNPS',74).
sigma('VBZ','NNS',73).
sigma('UH','UH',73).
sigma('VB','VB',72).
sigma('JJ','VBZ',72).
sigma('CC','MD',72).
sigma('WRB','VBD',71).
sigma('VBD','VB',71).
sigma('VBZ','PRP$',70).
sigma('NNP','WDT',70).
sigma('WRB','RB',69).
sigma('VBN','VBD',68).
sigma('NNP','JJ',68).
sigma('PRP','WRB',67).
sigma('DT','CC',67).
sigma('VB','CD',66).
sigma('RB','NNS',65).
sigma('VBZ','WRB',63).
sigma('RB','JJR',63).
sigma('CC','EX',63).
sigma('VBP','CC',62).
sigma('VBP','PRP$',60).
sigma('PRP$','RB',60).
sigma('PRP','NNP',60).
sigma('PRP$','IN',60).
sigma('CD','VBD',60).
sigma('TO','JJ',59).
sigma('DT','RBR',59).
sigma('WRB','.',58).
sigma('DT','MD',58).
sigma('CC','VBZ',58).
sigma('WP','RB',57).
sigma('VBD','EX',57).
sigma('VBP','NNS',56).
sigma('RB','EX',56).
sigma('PRP$','VBG',56).
sigma('WP','MD',54).
sigma('WDT','VBP',54).
sigma('TO','.',54).
sigma('NNP','NNPS',53).
sigma('NNP','CD',53).
sigma('JJR','CC',53).
sigma('.','TO',51).
sigma('NNS','VBZ',50).
sigma('NNS','NNP',50).
sigma('VBG','VBG',49).
sigma('RBR','RB',49).
sigma('NNP','WRB',48).
sigma('JJ','VBP',48).
sigma('CC','JJR',48).
sigma('JJS','NNS',47).
sigma('DT','VB',47).
sigma('WP','.',46).
sigma('VBZ','CD',46).
sigma('VBP','WP',46).
sigma('PRP','NNS',46).
sigma('NN','RP',46).
sigma('WRB','VBZ',45).
sigma('VBG','NNP',45).
sigma('PRP$','NNP',45).
sigma('VBN','CD',44).
sigma('NN','EX',44).
sigma('CD','RB',44).
sigma('CC','RBR',44).
sigma('PRP','WDT',43).
sigma('NNP','VBP',43).
sigma('JJR','NNS',43).
sigma('CD','TO',43).
sigma('WRB','TO',42).
sigma('WRB','NNP',41).
sigma('RP','NN',40).
sigma('JJ','PRP$',40).
sigma('WP','IN',39).
sigma('VBP','RP',39).
sigma('UH','NNP',39).
sigma('JJS','JJ',39).
sigma('JJR','.',39).
sigma('EX','VBP',39).
sigma('CD','PRP',39).
sigma('TO','NNS',38).
sigma('NNPS','.',38).
sigma('TO','CD',37).
sigma('NNPS','VBD',37).
sigma('RP','VBG',36).
sigma('NN','RBR',36).
sigma('WP','TO',35).
sigma('VBZ','VBD',35).
sigma('TO','VBG',35).
sigma('NNP','PRP$',35).
sigma('JJS','PRP',35).
sigma('WRB','MD',34).
sigma('WP','NN',34).
sigma('WDT','IN',34).
sigma('NN','UH',34).
sigma('VBZ','CC',33).
sigma('RP','VBD',33).
sigma('NNS','WRB',33).
sigma('MD','.',33).
sigma('JJ','VB',33).
sigma('IN','VBZ',33).
sigma('DT','PRP$',33).
sigma('CC','TO',33).
sigma('VB','JJR',32).
sigma('VBD','JJR',32).
sigma('NNS','VB',32).
sigma('DT','WP',32).
sigma('VBD','VBZ',31).
sigma('JJ','WRB',31).
sigma('JJR','JJ',31).
sigma('VBG','WP',30).
sigma('TO','WP',30).
sigma('RBR','IN',30).
sigma('NN','JJR',30).
sigma('DT','WDT',30).
sigma('VBP','NNP',29).
sigma('UH','CC',29).
sigma('.','JJS',29).
sigma('IN','VB',29).
sigma('WDT','NNS',28).
sigma('VBP','VB',28).
sigma('RBR','CC',28).
sigma('CD','WDT',28).
sigma('VB','WDT',27).
sigma('VBG','WRB',27).
sigma('VBD','RBR',27).
sigma('TO','RB',27).
sigma('RP','JJ',27).
sigma('NNP','VBN',27).
sigma('NNPS','IN',27).
sigma('JJR','RB',27).
sigma('IN','JJR',27).
sigma('NNS','PRP$',26).
sigma('MD','IN',26).
sigma('EX','MD',26).
sigma('VB','VBZ',25).
sigma('VBP','WRB',25).
sigma('VBP','VBZ',25).
sigma('VBP','CD',25).
sigma('UH','DT',25).
sigma('EX','PRP',25).
sigma('WRB','IN',24).
sigma('VB','PDT',24).
sigma('UH','NN',24).
sigma('RB','WDT',24).
sigma('RBR','.',24).
sigma('NNS','CD',24).
sigma('JJS','RB',24).
sigma('WRB','PRP$',23).
sigma('UH','WDT',23).
sigma('RP','WRB',23).
sigma('RP','WP',23).
sigma('PRP$','CC',23).
sigma('.','PDT',23).
sigma('VBN','WRB',22).
sigma('VBG','CD',22).
sigma('VBD','PDT',22).
sigma('MD','DT',22).
sigma('JJ','JJR',22).
sigma('CD','NNP',22).
sigma('VBZ','RP',21).
sigma('VBD','MD',21).
sigma('PRP$','VBN',21).
sigma('PRP','EX',21).
sigma('CD','VBZ',21).
sigma('WRB','VBN',20).
sigma('WP','NNP',20).
sigma('WDT','JJ',20).
sigma('VBD','UH',20).
sigma('PRP$','CD',20).
sigma('NNP','UH',20).
sigma('JJ','WP',20).
sigma('IN','NNPS',20).
sigma('CD','DT',20).
sigma('VBD','VBP',19).
sigma('UH','VB',19).
sigma('RP','PRP',19).
sigma('RP','NNP',19).
sigma('PRP','PRP$',19).
sigma('JJ','WDT',19).
sigma('JJ','MD',19).
sigma('EX','RB',19).
sigma('EX','.',19).
sigma('DT','TO',19).
sigma('WRB','NNS',18).
sigma('TO','WRB',18).
sigma('RBS','RB',18).
sigma('PRP','CD',18).
sigma('NNPS','CC',18).
sigma('MD','TO',18).
sigma('MD','NN',18).
sigma('IN','MD',18).
sigma('EX','DT',18).
sigma('CC','WDT',18).
sigma('WDT','PRP$',17).
sigma('VBP','EX',17).
sigma('VBG','PDT',17).
sigma('TO','WDT',17).
sigma('TO','IN',17).
sigma('RBR','NN',17).
sigma('PRP$','.',17).
sigma('NNS','RBR',17).
sigma('NN','PDT',17).
sigma('EX','IN',17).
sigma('DT','RP',17).
sigma('WRB','NN',16).
sigma('VBZ','EX',16).
sigma('VB','RBR',16).
sigma('VB','MD',16).
sigma('UH','IN',16).
sigma('RP','NNS',16).
sigma('RBR','NNS',16).
sigma('PRP$','JJS',16).
sigma('PRP$','DT',16).
sigma('JJR','TO',16).
sigma('IN','VBP',16).
sigma('CD','MD',16).
sigma('CD','JJR',16).
sigma('CC','CC',16).
sigma('VBZ','VBZ',15).
sigma('NNS','RP',15).
sigma('MD','VBN',15).
sigma('JJ','NNPS',15).
sigma('EX','CC',15).
sigma('CC','.',15).
sigma('VBN','PDT',14).
sigma('VBG','VBZ',14).
sigma('UH','FW',14).
sigma('RB','PDT',14).
sigma('PRP','UH',14).
sigma('JJS','CD',14).
sigma('EX','VBG',14).
sigma('WP','PRP$',13).
sigma('WP','NNS',13).
sigma('VBN','WP',13).
sigma('TO','CC',13).
sigma('MD','CC',13).
sigma('JJS','.',13).
sigma('CD','VBN',13).
sigma('WP$','NN',12).
sigma('VBZ','JJR',12).
sigma('VBN','WDT',12).
sigma('VB','EX',12).
sigma('UH','JJR',12).
sigma('UH','JJ',12).
sigma('RB','UH',12).
sigma('PRP','PDT',12).
sigma('.','NNPS',12).
sigma('JJ','UH',12).
sigma('JJS','VBD',12).
sigma('.','JJR',12).
sigma('DT','WRB',12).
sigma('CD','VBP',12).
sigma('CC','RBS',12).
sigma('CC','PDT',12).
sigma('WP','JJ',11).
sigma('VBZ','JJS',11).
sigma('VBP','VBP',11).
sigma('VBN','VBZ',11).
sigma('VBN','MD',11).
sigma('VBG','WDT',11).
sigma('VBD','WDT',11).
sigma('UH','WP',11).
sigma('UH','VBP',11).
sigma('.','RBR',11).
sigma('RB','JJS',11).
sigma('NN','WP$',11).
sigma('JJS','CC',11).
sigma('JJR','PRP',11).
sigma('JJ','JJS',11).
sigma('DT','EX',11).
sigma('CC','JJS',11).
sigma('VBZ','VB',10).
sigma('VBZ','RBS',10).
sigma('VBN','RBR',10).
sigma('VBG','JJR',10).
sigma('TO','PDT',10).
sigma('RBR','VBN',10).
sigma('PRP','RBR',10).
sigma('NNPS','VBP',10).
sigma('JJS','DT',10).
sigma('JJR','VBD',10).
sigma('VBZ','RBR',9).
sigma('VBD','JJS',9).
sigma('RP','VBN',9).
sigma('RP','CD',9).
sigma('RBR','PRP',9).
sigma('RBR','DT',9).
sigma('PDT','PRP$',9).
sigma('NNPS','RB',9).
sigma('FW','.',9).
sigma('CD','VBG',9).
sigma('WDT','TO',8).
sigma('VBG','VB',8).
sigma('VBG','MD',8).
sigma('UH','WRB',8).
sigma('TO','VBD',8).
sigma('RP','WDT',8).
sigma('RBR','VBD',8).
sigma('NNS','PDT',8).
sigma('NNP','EX',8).
sigma('JJ','PDT',8).
sigma('EX','NN',8).
sigma('.','.',8).
sigma('WRB','EX',7).
sigma('WDT','CD',7).
sigma('VB','VBP',7).
sigma('VBN','VBP',7).
sigma('VBN','JJR',7).
sigma('VBG','VBP',7).
sigma('VBG','RBR',7).
sigma('UH','VBN',7).
sigma('PRP$','WDT',7).
sigma('PRP$','VBD',7).
sigma('PRP$','RBS',7).
sigma('PRP$','PRP',7).
sigma('PRP','JJR',7).
sigma('PRP$','JJR',7).
sigma('NNS','EX',7).
sigma('NNPS','PRP',7).
sigma('NNPS','NNP',7).
sigma('NNPS','DT',7).
sigma('NN','JJS',7).
sigma('MD','NNP',7).
sigma('JJS','VB',7).
sigma('JJR','CD',7).
sigma('JJ','RBS',7).
sigma('DT','FW',7).
sigma('WRB','PDT',6).
sigma('WRB','CC',6).
sigma('WDT','VBG',6).
sigma('VBZ','WDT',6).
sigma('VBZ','UH',6).
sigma('VBZ','PDT',6).
sigma('VB','UH',6).
sigma('VBP','RBR',6).
sigma('VBP','PDT',6).
sigma('VBN','VB',6).
sigma('VBG','UH',6).
sigma('RP','VB',6).
sigma('RP','MD',6).
sigma('RBR','VBG',6).
sigma('RBR','VB',6).
sigma('RBR','CD',6).
sigma('NNPS','TO',6).
sigma('JJS','VBN',6).
sigma('JJ','EX',6).
sigma('IN','UH',6).
sigma('FW','FW',6).
sigma('WRB','WRB',5).
sigma('WRB','VBG',5).
sigma('WP','WDT',5).
sigma('WDT','WDT',5).
sigma('WDT','JJS',5).
sigma('VBP','WDT',5).
sigma('UH','TO',5).
sigma('RP','PDT',5).
sigma('RBR','WDT',5).
sigma('RB','RP',5).
sigma('PRP$','VBZ',5).
sigma('PRP$','TO',5).
sigma('PRP$','RP',5).
sigma('PRP','RBS',5).
sigma('NNS','WP$',5).
sigma('NNS','UH',5).
sigma('NNS','JJS',5).
sigma('NNS','JJR',5).
sigma('NNP','PDT',5).
sigma('NNP','JJR',5).
sigma('MD','WDT',5).
sigma('JJS','TO',5).
sigma('JJS','NNP',5).
sigma('FW','VBD',5).
sigma('FW','NN',5).
sigma('CD','WP',5).
sigma('CC','UH',5).
sigma('CC','RP',5).
sigma('WRB','VB',4).
sigma('WP$','NNS',4).
sigma('WP$','JJ',4).
sigma('VBP','RBS',4).
sigma('VBP','JJR',4).
sigma('VBN','EX',4).
sigma('UH','PRP$',4).
sigma('UH','NNS',4).
sigma('UH','MD',4).
sigma('RP','VBZ',4).
sigma('RBS','VBD',4).
sigma('RBS','NNS',4).
sigma('PRP$','VBP',4).
sigma('NNS','FW',4).
sigma('NNPS','WP',4).
sigma('NNPS','MD',4).
sigma('JJS','VBG',4).
sigma('JJR','RP',4).
sigma('JJ','RP',4).
sigma('JJR','DT',4).
sigma('FW','VBN',4).
sigma('FW','IN',4).
sigma('DT','UH',4).
sigma('CD','VB',4).
sigma('WRB','WDT',3).
sigma('WRB','CD',3).
sigma('WP','VBG',3).
sigma('WP','PDT',3).
sigma('WP$','JJS',3).
sigma('WP$','.',3).
sigma('WDT','EX',3).
sigma('WDT','CC',3).
sigma('VBN','RBS',3).
sigma('VBN','JJS',3).
sigma('VBD','RBS',3).
sigma('UH','VBZ',3).
sigma('TO','VBZ',3).
sigma('RP','VBP',3).
sigma('RP','RP',3).
sigma('RBS','VBN',3).
sigma('RBR','TO',3).
sigma('PRP$','MD',3).
sigma('PRP','FW',3).
sigma('NNP','WP$',3).
sigma('NNPS','VBG',3).
sigma('NNPS','NN',3).
sigma('NNPS','JJ',3).
sigma('NNP','RBR',3).
sigma('NN','FW',3).
sigma('MD','MD',3).
sigma('MD','CD',3).
sigma('JJS','VBP',3).
sigma('JJS','RBS',3).
sigma('JJR','MD',3).
sigma('IN','RBR',3).
sigma('IN','FW',3).
sigma('FW','VB',3).
sigma('FW','NNS',3).
sigma('FW','DT',3).
sigma('EX','WP',3).
sigma('EX','TO',3).
sigma('DT','LS',3).
sigma('WRB','UH',2).
sigma('WRB','JJS',2).
sigma('WRB','JJR',2).
sigma('WP','WP',2).
sigma('WP','JJS',2).
sigma('.','WP$',2).
sigma('WDT','VBN',2).
sigma('WDT','PDT',2).
sigma('VBZ','NNPS',2).
sigma('VBZ','MD',2).
sigma('VBP','UH',2).
sigma('VBP','MD',2).
sigma('VBP','JJS',2).
sigma('VBN','NNPS',2).
sigma('VB','JJS',2).
sigma('VBG','WP$',2).
sigma('VBD','WP$',2).
sigma('UH','VBG',2).
sigma('UH','EX',2).
sigma('TO','VBN',2).
sigma('TO','UH',2).
sigma('SYM','VBZ',2).
sigma('SYM','NNS',2).
sigma('SYM','DT',2).
sigma('RP','JJR',2).
sigma('RBR','NNP',2).
sigma('RBR','MD',2).
sigma('RB','FW',2).
sigma('PRP$','WP',2).
sigma('PRP','SYM',2).
sigma('NN','RBS',2).
sigma('NNPS','VB',2).
sigma('NNP','RP',2).
sigma('NNP','JJS',2).
sigma('MD','WRB',2).
sigma('MD','VBG',2).
sigma('LS','.',2).
sigma('JJS','WRB',2).
sigma('JJS','VBZ',2).
sigma('JJS','MD',2).
sigma('JJR','WRB',2).
sigma('JJR','VBZ',2).
sigma('JJR','VBP',2).
sigma('JJR','VBN',2).
sigma('JJR','VB',2).
sigma('JJR','UH',2).
sigma('JJR','NNP',2).
sigma('JJ','FW',2).
sigma('IN','WP$',2).
sigma('FW','RB',2).
sigma('FW','PRP',2).
sigma('FW','CC',2).
sigma('EX','JJ',2).
sigma('DT','SYM',2).
sigma('CD','WRB',2).
sigma('CD','NNPS',2).
sigma('CC','FW',2).
sigma('WRB','WP',1).
sigma('WP','WRB',1).
sigma('WP','VBN',1).
sigma('WP$','VBG',1).
sigma('WP','VB',1).
sigma('WP','UH',1).
sigma('WP$','PRP',1).
sigma('WP','NNPS',1).
sigma('WP','JJR',1).
sigma('WP','CD',1).
sigma('WP','CC',1).
sigma('WDT','WRB',1).
sigma('WDT','VB',1).
sigma('WDT','RBS',1).
sigma('WDT','RBR',1).
sigma('WDT','JJR',1).
sigma('VBZ','VBP',1).
sigma('VBZ','SYM',1).
sigma('VB','RBS',1).
sigma('VBP','NNPS',1).
sigma('VBN','UH',1).
sigma('VBN','FW',1).
sigma('VBG','NNPS',1).
sigma('VB','FW',1).
sigma('VBD','NNPS',1).
sigma('UH','SYM',1).
sigma('UH','RP',1).
sigma('UH','LS',1).
sigma('TO','VBP',1).
sigma('TO','TO',1).
sigma('TO','RP',1).
sigma('TO','RBR',1).
sigma('TO','NNPS',1).
sigma('TO','JJR',1).
sigma('SYM','SYM',1).
sigma('SYM','NNP',1).
sigma('SYM','FW',1).
sigma('SYM','CC',1).
sigma('RP','UH',1).
sigma('RP','JJS',1).
sigma('RP','EX',1).
sigma('RB','WP$',1).
sigma('RBS','VB',1).
sigma('RBS','TO',1).
sigma('.','RBS',1).
sigma('RBR','WRB',1).
sigma('RBR','WP',1).
sigma('RBR','VBZ',1).
sigma('RBR','RP',1).
sigma('RBR','JJR',1).
sigma('RBR','EX',1).
sigma('RB','NNPS',1).
sigma('PRP$','UH',1).
sigma('PRP$','PRP$',1).
sigma('PRP','NNPS',1).
sigma('PRP','JJS',1).
sigma('PRP$','EX',1).
sigma('NN','SYM',1).
sigma('NNS','RBS',1).
sigma('NNS','NNPS',1).
sigma('NNP','SYM',1).
sigma('NNPS','WDT',1).
sigma('NNPS','VBZ',1).
sigma('NNPS','NNS',1).
sigma('NNPS','NNPS',1).
sigma('NNPS','CD',1).
sigma('NNP','FW',1).
sigma('NN','NNPS',1).
sigma('MD','WP',1).
sigma('MD','VBZ',1).
sigma('MD','RBR',1).
sigma('MD','PRP$',1).
sigma('MD','NNS',1).
sigma('LS','DT',1).
sigma('LS','CC',1).
sigma('JJ','SYM',1).
sigma('JJS','PDT',1).
sigma('JJS','JJS',1).
sigma('JJR','WP',1).
sigma('JJR','VBG',1).
sigma('JJR','RBR',1).
sigma('JJR','PRP$',1).
sigma('JJR','PDT',1).
sigma('JJR','JJR',1).
sigma('JJR','EX',1).
sigma('FW','UH',1).
sigma('FW','RBR',1).
sigma('FW','JJ',1).
sigma('.','FW',1).
sigma('EX','WRB',1).
sigma('EX','WDT',1).
sigma('EX','VBN',1).
sigma('EX','PRP$',1).
sigma('EX','NNS',1).
sigma('EX','EX',1).
sigma('CD','RP',1).
sigma('CD','PRP$',1).
sigma('CD','PDT',1).
sigma('CD','JJS',1).
sigma('.','',1).
